apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
#cluster data & name
metadata: newproject
  name: 
  region: us-east-1
#managed by aws
managedNodeGroups:
  - name: spot
    instanceType: m5.large
    desiredCapacity: 2
    spot: true